huaweicloud/Sermant-website

docs/en/document/QuickStart.md
docs/en/document/UserGuide/README.md
docs/en/document/UserGuide/agentcore.md
docs/en/plugin/flowcontrol.md
docs/en/plugin/graceful.md
docs/en/plugin/loadbalancer.md
docs/zh/document/QuickStart.md
docs/zh/document/UserGuide/README.md
docs/zh/document/UserGuide/agentcore.md
docs/zh/plugin/flowcontrol.md
docs/zh/plugin/graceful.md
docs/zh/plugin/loadbalancer.md

【related-issue】#2
【description】update doc after remove demos and profile

update doc after remove demos and profile

---

docs/en/document/OperationGuide/injector.md
docs/zh/document/OperationGuide/injector.md

update doc for env configuration of injector

---

docs/en/document/user-guide/injector.md
docs/zh/document/user-guide/injector.md

【doc】修改injector文档，不再执行证书脚本，value.yaml不再填写caBundle

---

docs/.vuepress/config.js
docs/en/document/DeveloperGuide/dev-complex-plugin.md
docs/en/document/DeveloperGuide/dev-first-plugin.md
docs/zh/document/DeveloperGuide/dev-complex-plugin.md
docs/zh/document/DeveloperGuide/dev-first-plugin.md

【doc】开发者指南文档修改

---

docs/en/document/user-guide/injector.md
docs/zh/document/user-guide/injector.md

update doc for sermant-injector

---

docs/.vuepress/config.js
docs/en/document/developer-guide/version-manage.md
docs/zh/document/developer-guide/version-manage.md

[doc] add third party copyright and version management

---

docs/en/document/plugin/registry/springboot-registry.md
docs/zh/document/plugin/registry/springboot-registry.md

[doc] update springboot-registry plugin

---

docs/en/document/plugin/registry/README.md
docs/en/document/plugin/registry/dubbo-registry-migiration.md
docs/en/document/plugin/registry/spring-cloud-registry-migiration.md
docs/en/document/user-guide/sermant-agent.md
docs/zh/document/plugin/registry/README.md
docs/zh/document/plugin/registry/dubbo-registry-migiration.md
docs/zh/document/plugin/registry/spring-cloud-registry-migiration.md
docs/zh/document/user-guide/sermant-agent.md

【doc】修改注册插件文档

---

docs/en/document/plugin/router.md
docs/zh/document/plugin/router.md

【doc】修改路由插件文档

---

docs/en/document/plugin/dynamic-config.md
docs/en/document/plugin/flowcontrol.md
docs/zh/document/plugin/dynamic-config.md
docs/zh/document/plugin/flowcontrol.md

【修复issue】#24
【修改内容】修改流控和动态配置插件文档

更新流控和动态配置插件文档

---

docs/en/document/plugin/visibility.md
docs/zh/document/plugin/visibility.md

[doc] update visibility plugin

---

docs/zh/document/plugin/monitor.md

[doc] update monitor plugin

---

docs/en/document/user-guide/readme.md
docs/en/document/user-guide/sermant-agent.md
docs/zh/document/user-guide/backend.md
docs/zh/document/user-guide/readme.md
docs/zh/document/user-guide/sermant-agent.md

[doc] fix user-guide problem

---

docs/zh/document/developer-guide/README.md

【doc】修改创建首个插件时的mvn指令

---

docs/en/document/plugin/monitor.md
docs/en/document/plugin/visibility.md
docs/en/document/user-guide/sermant-agent.md
docs/zh/document/plugin/monitor.md
docs/zh/document/plugin/visibility.md
docs/zh/document/user-guide/sermant-agent.md

[doc] update monitor & visibility plugin

---

docs/en/document/plugin/graceful.md
docs/zh/document/plugin/graceful.md

[doc] update graceful plugin

---

docs/en/document/plugin/registry/springboot-registry.md
docs/zh/document/plugin/registry/springboot-registry.md

[doc] update springboot registry plugin

---

docs/en/document/plugin/dynamic-config.md
docs/en/document/plugin/flowcontrol.md
docs/zh/document/plugin/dynamic-config.md
docs/zh/document/plugin/flowcontrol.md

[doc] update dynamic config and flowcontrol plugin

---

docs/en/document/plugin/README.md
docs/en/document/plugin/registry/README.md
docs/zh/document/plugin/README.md
docs/zh/document/plugin/registry/README.md
docs/zh/document/plugin/router.md

[doc] update registry

---

docs/zh/document/developer-guide/package-structure.md

插件结构&插件服务开发指导

---

docs/zh/document/developer-guide/plugin-configuration.md

【doc】修改插件配置文档

---

docs/zh/document/plugin/graceful.md

[doc] update graceful md

---

docs/zh/document/plugin/graceful.md
docs/zh/document/plugin/register-migration.md

[doc] bug fix

---

docs/en/blog/README.md
docs/zh/blog/README.md

[doc] add Java Agent 场景性能测试分析优化经验分享

---

docs/.vuepress/components/HomePage.vue
docs/en/README.md
docs/en/blog/README.md
docs/zh/README.md
docs/zh/blog/README.md

主页中心增加博客按钮

---

docs/.vuepress/components/HomePage.vue
docs/.vuepress/config.js
docs/.vuepress/styles/index.styl
docs/.vuepress/theme/components/Navbar.vue

【feature】修改页面样式

---

docs/.vuepress/config.js

【修复issue】#issue号
【修改内容】增加/修改/删除了xxx
------
/feat
Fixes #

回滚config.js

---

docs/.vuepress/config.js

【修复issue】#issue号
【修改内容】增加/修改/删除了xxx
------
/feat
Fixes #

Version support

---

docs/.vuepress/theme/components/Navbar.vue

【修复issue】#issue号
【修改内容】增加/修改/删除了xxx
------
/feat
Fixes #

回滚NavBar组件

---

docs/.vuepress/config.js

【enhance】增加多版本支持

---

.github/workflows/build.yml
.github/workflows/preview.yml
docs/.vuepress/components/Versions.vue
docs/.vuepress/util/index.js

【修复issue】#162
【修改内容】创建编译检查，修改检查version-support分支为检查develop分支

创建编译检查，修改检查version-support分支为检查develop分支

---

docs/.vuepress/config.js

【修复issue】#165
【修改内容】1、回滚使用手册中Backed和Agent关于1.1.x版本特性的文档 2、删除服务可见性文档，服务可见性为1.1.x版本的特性

修改config.js根路径

---

docs/zh/document/plugin/router.md

【修复issue】 #110 
【修改内容】增加了染色规则的描述

路由插件增加染色文档

---

docs/zh/document/plugin/router.md

【修复issue】 #110 
【修改内容】添加同标签路由能力文档

添加同标签路由能力文档

---

docs/en/document/plugin/flowcontrol.md
docs/zh/document/plugin/flowcontrol.md

【修复issue】#147
【修改内容】治理文档中的Match改为match

治理中Match配置改为match
